insert into Categoria (nome) values ('Bebidas');
insert into Categoria (nome) values ('Carne');
insert into Fabricante (nome) values ('JBS');
insert into Fabricante (nome) values ('The Coca Cola');
insert into Produto (nome, quantidade, preco, validade, categoria_codigo, fabricante_codigo) values ('Coca Cola', 100, 7.50, '2025-09-01', 1, 2);
insert into Produto(nome, quantidade, preco, validade, categoria_codigo, fabricante_codigo) values ('Carne', 50, 25.00, '2024-06-15', 2, 1);
insert into Produto(nome, quantidade, preco, validade, categoria_codigo, fabricante_codigo) values ('Frango', 80, 15.00, '2024-07-20', 3, 1);
insert into Produto(nome, quantidade, preco, validade, categoria_codigo, fabricante_codigo) values ('Suco de Laranja', 120, 5.00, '2025-08-10', 4, 2);
insert into Funcionario (nome, cargo, salario) values ('Edvan', 'Gerente', 4500.00);
insert into Funcionario (nome, cargo, salario) values ('Ramon', 'Vendedor', 3000.00);
insert into Funcionario (nome, cargo, salario) values ('Marcelo', 'Caixa', 2500.00);
insert into Funcionario (nome, cargo, salario) values ('Gustavo', 'Estoquista', 2800.00);
insert into Cliente (nome, email, telefone) values ('Edvan', 'edvan1552@gmail.com', '1234-5678');
insert into Cliente (nome, email, telefone) values ('Gustavo', 'gustavo2442@gmail.com', '9876-5432');
insert into Cliente (nome, email, telefone) values ('Ramon', 'ramon6632@gmail.com', '4321-8765');
insert into Cliente (nome, email, telefone) values ('Marcelo', 'marcelo1234@gmail.com', '8765-4321');
insert into Venda (data, total, funcionario_codigo, cliente_codigo) values ('2024-06-01', 75.00, 2, 1);
insert into Venda (data, total, funcionario_codigo, cliente_codigo) values ('2024-06-02', 50.00, 2, 2);
insert into ItemVenda (venda_codigo, produto_codigo, quantidade, preco) values (1, 1, 5, 7.50);
insert into ItemVenda (venda_codigo, produto_codigo, quantidade, preco) values (1, 2, 1, 25.00);
insert into ItemVenda (venda_codigo, produto_codigo, quantidade, preco) values (2, 3, 2, 15.00);
insert into ItemVenda (venda_codigo, produto_codigo, quantidade, preco) values (2, 4, 5, 5.00);     
insert into ItemVenda (venda_codigo, produto_codigo, quantidade, preco) values (1, 4, 3, 5.00);
